<?php

namespace AppBundle\Repository;

/**
 * BookOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
